// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqP03DnkZCnp09NArb-e7rAPxZ6dZLauk',
    appId: '1:6186204465:web:5fefb8affb490993880410',
    messagingSenderId: '6186204465',
    projectId: 't-store-31622',
    authDomain: 't-store-31622.firebaseapp.com',
    storageBucket: 't-store-31622.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs0zDGUIzXmHCR8oKzC2OiILl-nWOfy0g',
    appId: '1:6186204465:android:18acf553a076533e880410',
    messagingSenderId: '6186204465',
    projectId: 't-store-31622',
    storageBucket: 't-store-31622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy0goHvSDIjpEAKcpmjLnKF6UiRqCPxSY',
    appId: '1:6186204465:ios:1dd1790d7fdc7417880410',
    messagingSenderId: '6186204465',
    projectId: 't-store-31622',
    storageBucket: 't-store-31622.firebasestorage.app',
    iosBundleId: 'com.example.tStoreAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy0goHvSDIjpEAKcpmjLnKF6UiRqCPxSY',
    appId: '1:6186204465:ios:1dd1790d7fdc7417880410',
    messagingSenderId: '6186204465',
    projectId: 't-store-31622',
    storageBucket: 't-store-31622.firebasestorage.app',
    iosBundleId: 'com.example.tStoreAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqP03DnkZCnp09NArb-e7rAPxZ6dZLauk',
    appId: '1:6186204465:web:4a350c2cb85cc3a5880410',
    messagingSenderId: '6186204465',
    projectId: 't-store-31622',
    authDomain: 't-store-31622.firebaseapp.com',
    storageBucket: 't-store-31622.firebasestorage.app',
  );
}
