// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYhpibvXqOU6z0zQhMycn8J1TIOO3zd2k',
    appId: '1:15877949110:web:e41b5cd7ee0ecb68f58817',
    messagingSenderId: '15877949110',
    projectId: 'new-church-77e88',
    authDomain: 'new-church-77e88.firebaseapp.com',
    databaseURL: 'https://new-church-77e88-default-rtdb.firebaseio.com',
    storageBucket: 'new-church-77e88.appspot.com',
    measurementId: 'G-7EZ27WD2ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMOpSfITvD3A4sw29nInvlx5tmTq7kYa8',
    appId: '1:15877949110:android:52d9fe4fa324257cf58817',
    messagingSenderId: '15877949110',
    projectId: 'new-church-77e88',
    databaseURL: 'https://new-church-77e88-default-rtdb.firebaseio.com',
    storageBucket: 'new-church-77e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3iTmP1o9c-84g86fPF1j4LQifcUZ7LjU',
    appId: '1:15877949110:ios:a61affaa838282d7f58817',
    messagingSenderId: '15877949110',
    projectId: 'new-church-77e88',
    databaseURL: 'https://new-church-77e88-default-rtdb.firebaseio.com',
    storageBucket: 'new-church-77e88.appspot.com',
    iosBundleId: 'com.example.tStoreAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3iTmP1o9c-84g86fPF1j4LQifcUZ7LjU',
    appId: '1:15877949110:ios:a61affaa838282d7f58817',
    messagingSenderId: '15877949110',
    projectId: 'new-church-77e88',
    databaseURL: 'https://new-church-77e88-default-rtdb.firebaseio.com',
    storageBucket: 'new-church-77e88.appspot.com',
    iosBundleId: 'com.example.tStoreAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYhpibvXqOU6z0zQhMycn8J1TIOO3zd2k',
    appId: '1:15877949110:web:e41b5cd7ee0ecb68f58817',
    messagingSenderId: '15877949110',
    projectId: 'new-church-77e88',
    authDomain: 'new-church-77e88.firebaseapp.com',
    databaseURL: 'https://new-church-77e88-default-rtdb.firebaseio.com',
    storageBucket: 'new-church-77e88.appspot.com',
    measurementId: 'G-7EZ27WD2ET',
  );

}